import {Open_Sans} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageTransition from "@/components/PageTransition";
// import StairTransition from "@/components/StairTransition";


const open_sans = Open_Sans({
  subsets: ["latin"], 
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={open_sans.variable}>
          <Header />
          {/* <StairTransition /> */}
          <PageTransition>{children}</PageTransition>
        </body>
      </html>
  );
}
